### PR TITLE
Make ControlSizeTrigger consistent with AdaptiveTrigger + fix conditional

### LINKED ISSUE #737: Make ControlSizeTrigger consistent with AdaptiveTrigger + bug fix
**Describe the bug**
Unlike AdaptiveTrigger, the visual state will never be triggered if you write the following code: `<trigger:ControlSizeTrigger MinWidth="0" />` which can be very useful for future PR.

Similarly, the current code doesn't work if the control associated is already fully loaded.

(the original control in https://github.com/microsoft/Windows-universal-samples/blob/master/Samples/XamlStateTriggers/cs/CustomTriggers/ControlSizeTrigger.cs has the same issues, which should also be fixed)

In addition to this improvement, we also need to fix a bug in the following code:
`if (Source != nullptr && MinWidth >= 0 || MinHeight >= 0)`
which is equivalent to 
`if ((Source != nullptr && MinWidth >= 0) || MinHeight >= 0)`
and not 
`if (Source != nullptr && (MinWidth >= 0 || MinHeight >= 0))`
which was, I suppose, the intention.

**Device and Application Information**
 - OS Build: 10.0.18363.0
 - Architecture: X64
 - Application Version: 10.1908.0.0
 - Region: en-US
 - Dev Version Installed: True

**Requested Assignment**
If possible, I would like to fix this.

### PR DESCRIPTION
**Pull request by rudyhuyn**
### Description of the changes:
- fix conditional
- make `MinWidth` and `MinHeight` equal to -1 by default (same than AdaptiveTrigger)
- support Visual State trigger with `MinWidth="0"` or `MinHeight="0"`
- decrease the number of conditionals in `ControlSizeTrigger::UpdateIsActive`
- make ControlSizeTrigger works even if the control is already loaded (SizeChanged not called)

### How changes were validated:
- manually with the Calculator + a test app

### CODE REVIEW

File: src/Calculator/Views/StateTriggers/ControlSizeTrigger.cpp [hunk 1]
```diff
@@ -51,30 +53,19 @@ void ControlSizeTrigger::UnregisterSizeChanged(FrameworkElement^ element)
...
-        else
-        {
-            SetActive(sourceSize.Width >= MinWidth);
-        }
+        SetActive(sourceSize.Height >= MinHeight && (MinWidth < 0 || sourceSize.Width >= MinWidth));
     }
     else
     {
-        SetActive(false);
+        SetActive(MinWidth >= 0 && sourceSize.Width >= MinWidth);
```
Comment (rudyhuyn) [inline src/Calculator/Views/StateTriggers/ControlSizeTrigger.cpp]: We can remove `MinWidth>=0` because sourceSize _should_ always be >= 0, but I prefer to keep it to be sure this assumption is and will always be true
