### PR TITLE
Fix issue with Date diff when it includes a Daylight Saving Time

### LINKED ISSUE #178: Wrong Date Calculation on last Saturday to Sunday in March
**Describe the bug**
The Date Calculator does not factor in the last Saturday to Sunday every March (ex. 2017/03/25 - 2017/03/26).
Because of that the Calculation of the whole month is also wrong.

**Steps To Reproduce**
1. Go to the Date Calculator
2. Select 30. March 2019 and 31. March 2019
3. The Calculator says its the same Date.

**Expected behavior**
If you do the steps above it should show a 1Day difference.
If you select the whole Month of March it says its 29 Days. The right answer would be 30 Days.

**Screenshots**
image
image

**Device and Application Information:**
 - OS Build: 10.0.17763.0
 - Architecture: X64
 - Application Version: 10.1812.10048.0

### PR DESCRIPTION
**Pull request by rudyhuyn**
## Fixes #178 

The application uses local time to calculate the number of days between 2 dates. If a Daylight Saving Time takes place during this period of time (only Clocks Forward 2am->3am), the application will miss 1 day and fail to calculate the number of days/weeks/months between the 2 dates.
image
### Description of the changes:

`DateCalculationEngine` uses local time to modify dates, however, `AddDays`, `AddWeeks`,... won't add 24 hours or 7 days if DST happens between the 2 dates, but instead add ~23.9/24.1 hours or ~6.9/7.1 days (depends if it's the DST clock backward or clock forward). When the DST is clock forward, `DateCalculationEngine` will miss one day.

### Solution
- use UTC dates to calculate date difference.
Extra Fix:
- use `calendar->FirstPeriodInThisDay` and `calendar->FirstHourInThisPeriod` in ClipTime (else it will set the time to 12PM (noon) in some regions.
- replace `OBSERVABLE_PROPERTY_RW` by `OBSERVABLE_PROPERTY_R` when possible.
- remove  the definition of `CheckClipTimeSameDay` (implementation missing)

### How changes were validated:

Tested manually with different regions (FR, US, ES, JP).

### CODE REVIEW

**Comment by rudyhuyn** [comment]
It probably also explains this comment in the code:

>   In the ClipTime function, we used to change timezone to UTC before clipping the time.
     The comment from the previous delopers said this was done to eliminate the effects of
     Daylight Savings Time. We can't think of a good reason why this change in timezone is
     necessary and did find bugs related to the change, therefore, we have removed the
     change. Just in case, we will see if the clipped time is ever a different day from the
     original day, which would hopefully indicate the change in timezone was actually
     necessary. We will collect telemetry if we find this case. If we don't see any
     telemetry events after the application has been used for some time, we will feel safe
     and can remove this function.

**Comment by jlaanstra** [comment]
This change makes sense to me. We don't deal with time and therefore should do these calculations in UTC.

**Comment by michael-hawker** [comment]
Should some Unit Tests be added as a safety for this logic?

File: src/CalcViewModel/DateCalculatorViewModel.cpp [hunk 1]
```diff
@@ -378,13 +372,14 @@ String^ DateCalculatorViewModel::GetLocalizedNumberString(int value) const
     return ref new String(numberStr.c_str());
 }
 
-// Adjusts the given DateTime to 12AM of the same day
+// Adjusts the given DateTime to 12AM (UTC) of the same day
```
Comment (jsoref) [inline src/CalcViewModel/DateCalculatorViewModel.cpp]: Personally I'd suggest avoiding adding trailing whitespace here

File: src/Calculator/Views/DateCalculator.xaml.cpp [hunk 2]
```diff
@@ -36,8 +36,6 @@ using namespace Windows::UI::Xaml::Input;
 using namespace Windows::UI::Xaml::Media;
 using namespace Windows::UI::Xaml::Navigation;
 
-// The User Control item template is documented at https://go.microsoft.com/fwlink/?LinkId=234236
```
Comment (jsoref) [inline src/Calculator/Views/DateCalculator.xaml.cpp]: This change _feels_ unrelated

File: src/CalculatorUnitTests/DateCalculatorUnitTests.cpp [hunk 3]
```diff
@@ -1,4 +1,4 @@
-﻿// Copyright (c) Microsoft Corporation. All rights reserved.
+// Copyright (c) Microsoft Corporation. All rights reserved.
```
Comment (jsoref) [inline src/CalculatorUnitTests/DateCalculatorUnitTests.cpp]: This change _feels_ unrelated (and I think I've seen it i a number of PRs)

File: src/CalculatorUnitTests/DateCalculatorUnitTests.cpp [hunk 4]
```diff
@@ -387,6 +387,65 @@ namespace DateCalculationUnitTests
...
+          viewModel->FromDate = DateUtils::SystemTimeToDateTime(datetimeDifftest[5].startDate);
+          /*31.03.2008*/
+          viewModel->ToDate = DateUtils::SystemTimeToDateTime(datetimeDifftest[5].endDate);
+
+          //// Assert for the result
+          VERIFY_IS_FALSE(viewModel->IsDiffInDays);
+          VERIFY_ARE_EQUAL(StringReference(L"31 days"), viewModel->StrDateDiffResultInDays);
+          VERIFY_ARE_EQUAL(StringReference(L"1 month, 2 days"), viewModel->StrDateDiffResult);
+
+          // Daylight saving time - Clock Forward
```
Comment (jsoref) [inline src/CalculatorUnitTests/DateCalculatorUnitTests.cpp]: `Daylight Saving Time` is a proper noun, please capitalize all 3 items :-)

File: src/CalculatorUnitTests/DateCalculatorUnitTests.cpp [hunk 5]
```diff
@@ -387,6 +387,65 @@ namespace DateCalculationUnitTests
...
+
+          viewModel->IsDateDiffMode = true;
+          VERIFY_IS_TRUE(viewModel->IsDateDiffMode);
+
+          /*29.02.2008*/
+          viewModel->FromDate = DateUtils::SystemTimeToDateTime(datetimeDifftest[5].startDate);
+          /*31.03.2008*/
+          viewModel->ToDate = DateUtils::SystemTimeToDateTime(datetimeDifftest[5].endDate);
+
+          //// Assert for the result
```
Comment (jsoref) [inline src/CalculatorUnitTests/DateCalculatorUnitTests.cpp]: I'm not sure about the style in calc, but I'd half expect this comment to be unnecessary (it should be obvious that VERIFY_... is asserting).

File: src/CalculatorUnitTests/DateCalculatorUnitTests.cpp [hunk 6]
```diff
@@ -387,6 +387,65 @@ namespace DateCalculationUnitTests
...
         }
 
+        TEST_METHOD(DateCalcViewModelDateDiffDaylightSavingTimeTest)
+        {
+          auto viewModel = ref new DateCalculatorViewModel();
+
+          viewModel->IsDateDiffMode = true;
+          VERIFY_IS_TRUE(viewModel->IsDateDiffMode);
+
+          /*29.02.2008*/
```
Comment (jsoref) [inline src/CalculatorUnitTests/DateCalculatorUnitTests.cpp]: I'm not sure what date format calc normally uses internally, but i'd encourage YYYY-MM-DD as opposed to DD-MM-YYYY. The standard US format is MM-DD-YYYY and thus using DD-MM-YYYY is fairly unexpected and at times ambiguous. Since no one writes YYYY-DD-MM, using YYYY-MM-DD is unambiguous and fairly easy for people to understand.

File: src/Calculator/Views/DateCalculator.xaml.cpp [hunk 7]
```diff
@@ -36,6 +36,7 @@ using namespace Windows::UI::Xaml::Input;
 using namespace Windows::UI::Xaml::Media;
 using namespace Windows::UI::Xaml::Navigation;
 
+// The User Control item template is documented at https://go.microsoft.com/fwlink/?LinkId=234236
```
Comment (jlaanstra) [inline src/Calculator/Views/DateCalculator.xaml.cpp]: Remove.

File: src/CalcViewModel/DateCalculatorViewModel.cpp [hunk 8]
```diff
@@ -43,11 +43,7 @@ DateCalculatorViewModel::DateCalculatorViewModel() :
     m_StrDateDiffResultAutomationName(L""),
     m_StrDateDiffResultInDays(L""),
     m_StrDateResult(L""),
-    m_StrDateResultAutomationName(L""),
-    m_fromDate({ 0 }),
```
Comment (HowardWolosky) [inline src/CalcViewModel/DateCalculatorViewModel.cpp]: What's your argument for removing the explicit initialization here?

File: src/CalcViewModel/DateCalculatorViewModel.cpp [hunk 9]
```diff
@@ -378,13 +372,14 @@ String^ DateCalculatorViewModel::GetLocalizedNumberString(int value) const
...
-// Adjusts the given DateTime to 12AM of the same day
+// Adjusts the given DateTime to 12AM (UTC) of the same day 
 DateTime DateCalculatorViewModel::ClipTime(DateTime dateTime)
 {
     auto calendar = ref new Calendar();
+    calendar->ChangeTimeZone("UTC");
     calendar->SetDateTime(dateTime);
-    calendar->Period = 1;
-    calendar->Hour = 12;
+    calendar->Period = calendar->FirstPeriodInThisDay;
```
Comment (HowardWolosky) [inline src/CalcViewModel/DateCalculatorViewModel.cpp]: Nice. Didn't know these properties existed. 👍

File: src/CalcViewModel/DateCalculatorViewModel.cpp [hunk 10]
```diff
@@ -56,19 +52,17 @@ DateCalculatorViewModel::DateCalculatorViewModel() :
 
     // Initialize Date Calc engine
     m_dateCalcEngine = make_shared<DateCalculationEngine>(localizationSettings.GetCalendarIdentifier());
-
     // Initialize dates of DatePicker controls to today's date
     auto calendar = ref new Calendar();
+    calendar->ChangeTimeZone("UTC");
```
Comment (HowardWolosky) [inline src/CalcViewModel/DateCalculatorViewModel.cpp]: The comment at line 83 (that you referenced in another comment) should be removed now.  Leaving it as is will be confusing, because you now _are_ changing he timezone to `UTC` before calling `ClipTime`.  Can you just add a simpler comment here that it's being done to avoid issues around Daylight Savings Time?

File: src/CalcViewModel/DateCalculatorViewModel.h [hunk 11]
```diff
@@ -23,7 +23,7 @@ namespace CalculatorApp
             // Input Properties
             OBSERVABLE_PROPERTY_RW(bool, IsDateDiffMode);
             OBSERVABLE_PROPERTY_RW(bool, IsAddMode);
-            OBSERVABLE_PROPERTY_RW(bool, IsDiffInDays);     // If diff is only in days or the dates are the same,
+            OBSERVABLE_PROPERTY_R(bool, IsDiffInDays);     // If diff is only in days or the dates are the same,
```
Comment (HowardWolosky) [inline src/CalcViewModel/DateCalculatorViewModel.h]: nit: Annoying, but can you re-line up the split-line comment here with the one below it?

File: src/Calculator/Views/DateCalculator.xaml.cpp [hunk 12]
```diff
@@ -37,7 +37,6 @@ using namespace Windows::UI::Xaml::Media;
 using namespace Windows::UI::Xaml::Navigation;
 
 // The User Control item template is documented at https://go.microsoft.com/fwlink/?LinkId=234236
```
Comment (HowardWolosky) [inline src/Calculator/Views/DateCalculator.xaml.cpp]: Seems like this file can be reverted.

File: src/CalcViewModel/Common/DateCalculator.cpp [hunk 13]
```diff
@@ -12,6 +12,7 @@ using namespace CalculatorApp::Common::DateCalculation;
 DateCalculationEngine::DateCalculationEngine(_In_ String^ calendarIdentifier)
 {
     m_calendar = ref new Calendar();
+    m_calendar->ChangeTimeZone("UTC");
```
Comment (HowardWolosky) [inline src/CalcViewModel/Common/DateCalculator.cpp]: Worthwhile to add a comment into here as to why.  This has clearly been a question that has come up in the code in the past.

File: src/CalcViewModel/DateCalculatorViewModel.cpp (hunk 8 above)
Comment (rudyhuyn) [reply src/CalcViewModel/DateCalculatorViewModel.cpp]: These 4 objects are initialized in the constructor lines 61-65, these 4 lines weren't necessary

File: src/CalcViewModel/DateCalculatorViewModel.cpp [hunk 14]
```diff
@@ -54,6 +54,8 @@ DateCalculatorViewModel::DateCalculatorViewModel() :
     m_dateCalcEngine = make_shared<DateCalculationEngine>(localizationSettings.GetCalendarIdentifier());
     // Initialize dates of DatePicker controls to today's date
     auto calendar = ref new Calendar();
+    // We force the timezone to UTC, to be sure to not being affected by Daylight Saving Time
```
Comment (HowardWolosky) [inline src/CalcViewModel/DateCalculatorViewModel.cpp]: `to be sure to not being` -> `to avoid being`

File: src/CalculatorUnitTests/DateCalculatorUnitTests.cpp [hunk 15]
```diff
@@ -387,6 +387,63 @@ namespace DateCalculationUnitTests
...
         }
 
+        TEST_METHOD(DateCalcViewModelDateDiffDaylightSavingTimeTest)
+        {
+          auto viewModel = ref new DateCalculatorViewModel();
+
+          viewModel->IsDateDiffMode = true;
+          VERIFY_IS_TRUE(viewModel->IsDateDiffMode);
+
+          // 29.02.2008
```
Comment (HowardWolosky) [inline src/CalculatorUnitTests/DateCalculatorUnitTests.cpp]: It looks like you forgot to make these two dates  be M-D-Y like the others that you had changed in a previous update.

Comment (rudyhuyn) [reply src/CalculatorUnitTests/DateCalculatorUnitTests.cpp]: all the dates in this file are dd.mm.yyyy (see line 275). The few dates I added use the same format

Comment (HowardWolosky) [reply src/CalculatorUnitTests/DateCalculatorUnitTests.cpp]: Right you are.  I misread the code.  Apologies.

**Comment by rogersachan** [comment]
@HowardWolosky I think this bug has resurfaced according to this reddit post <https://www.reddit.com/r/Windows10/comments/c14fu5/wait_what/>

image

Poster below claims it can be reproduced on the 1905 version.

**Comment by rogersachan** [comment]
image
`Calculator 10.1904.42.0
© 2019 Microsoft. All rights reserved.`

**Comment by HowardWolosky** [comment]
Thanks for the heads-up, @rogersachan.  The two issues aren't actually related, but the reddit thread is completely right about there being a bug.  @Bigpet opened #552 which is tracking the issue you're calling attention to (and also managed to supply a proposed fix with #553 as well!), so we'll keep _this_ issue closed for now and continue using #552 to track this new bug.  Thanks for the report though!
