### PR TITLE
Fix issue #1782

### LINKED ISSUE #1782: Access key input is captured in the input box
**Describe the bug**

The keyboard input was captured in access key mode.

**Steps To Reproduce**

Scenario 1:
1. Open navigation view
2. Press "2" on the keyboard
3. Observe the text box after navigating to scientific mode: "2" is shown up

Scenario 2:
1. Navigate to standard, scientific or programmer mode
2. Press Alt key to enter access key mode
3. Press any number on the keyboard
4. Observe the text box: the numbers are shown up

**Expected behavior**

Access key input shall not be captured in the input box.

**Screenshots**
image

image

image

**Device and Application Information**
 - OS Build: 22000.434
 - Architecture: x64
 - Application Version: 11.2201.3.0
 - Region: en-US
 - Dev Version Installed: No

**Additional context**
N/A

**Requested Assignment**
N/A

### PR DESCRIPTION
**Pull request by jbaylon3**
### Description of the changes:
-When using Access Keys to change the calculator mode, the Mode Property change happens after the KeyDown event, but before CharacterReceived is handled. Therefore, causing the keyboard shortcuts to be enables while the CharacterReceived event is still happening.  This made the keyboard input made for the Access Key being processed as a Calculator input. With these changes, we can detect if there is still a keyboard input still pending, and if that is the case defer re-enabling keyboard shortcuts until the current key sequence in completed. 

### How changes were validated:

-Manual testing. 
-
-

### CODE REVIEW

File: src/Calculator/Common/KeyboardShortcuManager.cs [hunk 1]
```diff
@@ -714,6 +717,29 @@ private static void OnKeyDownHandler(CoreWindow sender, KeyEventArgs args)
...
+
+            public static void TryEnableShortcut()
+            {
+                if (s_keyHandlerCount > 0)
+                {
+                    s_deferredEnableShortcut = true;
+                }
+                else
+                {
+                    KeyboardShortcutManager.DisableShortcuts(true);
```
Comment (DefaultRyan) [inline src/Calculator/Common/KeyboardShortcuManager.cs:739]: This should be passing `false`. In both cases, we should be passing the same value and getting the same behavior - the only difference is whether it happens immediately in `TryEnableShortcut` or later in `OnKeyUpHandler`.

**Review by DefaultRyan — CHANGES_REQUESTED** [review]

File: src/Calculator/Common/KeyboardShortcuManager.cs [hunk 2]
```diff
@@ -249,6 +249,7 @@ internal static void Initialize()
                 var coreWindow = Window.Current.CoreWindow;
                 coreWindow.CharacterReceived += OnCharacterReceivedHandler;
                 coreWindow.KeyDown += OnKeyDownHandler;
+                coreWindow.KeyUp += OnKeyUpHandler;
```
Comment (hanzhang54) [inline src/Calculator/Common/KeyboardShortcuManager.cs:252]: It seems unnecessary to listen to the `KeyUp` event. Since the root cause is the `CharacterReceived` event still happening after `AcceleratorKeyActivated` event, here is an easier fix by checking whether the event args have already been handled like in `OnKeyDownHandler()`.

Comment (jbaylon3) [reply src/Calculator/Common/KeyboardShortcuManager.cs:252]: The value of "handled" is the same whether the user is entering normal input or if they are using an AccessKey. The calculator was attempting to perform this by disabling keyboard shortcuts while the nav pane is still open. But re-enabling keyboard shortcuts when the nav pane closes and/or during a mode change is too soon which led to the access key input being captured in the input box. So, by tracking the KeyDown/KeyUp counter we can wait until the current keyboard interaction is complete and re-enable keyboard shortcuts then.

Comment (DefaultRyan) [reply src/Calculator/Common/KeyboardShortcuManager.cs:252]: Friendly ping. Is this still being reviewed?

Thanks
Ryan

Comment (jbaylon3) [reply src/Calculator/Common/KeyboardShortcuManager.cs:252]: Yes, It is still being reviewed

Comment (DefaultRyan) [reply src/Calculator/Common/KeyboardShortcuManager.cs:252]: Sorry for not being clear. I was asking about @hanzhang54, who had started looking at this. Hadn't seen a reply to jbaylon's explanation yet, so wanted to ensure this is still being looked at.

**Review by DefaultRyan — APPROVED** [review]

File: src/Calculator/Common/KeyboardShortcuManager.cs (hunk 2 above)
Comment (DefaultRyan) [reply src/Calculator/Common/KeyboardShortcuManager.cs:252]: Hi again, @hanzhang54 , do you anticipate being able to get back to reviewing this?

Thanks

Comment (hanzhang54) [reply src/Calculator/Common/KeyboardShortcuManager.cs:252]: Sorry for the delay. I made a mistake on the handled event, and you are right about the same handled value whether it is normal input or the access key input. Tracking the KeyDown/KeyUp counter looks good to me.

File: src/Calculator/Common/KeyboardShortcuManager.cs [hunk 3]
```diff
@@ -630,6 +631,7 @@ private static void OnVirtualKeyControlShiftChordPropertyChanged(DependencyObjec
             private static void OnCharacterReceivedHandler(CoreWindow sender, CharacterReceivedEventArgs args)
             {
                 int viewId = Utilities.GetWindowId();
+
```
Comment (hanzhang54) [inline src/Calculator/Common/KeyboardShortcuManager.cs:634]: Please remove the extra empty line.

File: src/Calculator/Common/KeyboardShortcuManager.cs [hunk 4]
```diff
@@ -714,6 +717,29 @@ private static void OnKeyDownHandler(CoreWindow sender, KeyEventArgs args)
...
 
+            private static void OnKeyUpHandler(CoreWindow sender, KeyEventArgs args)
+            {
+                s_keyHandlerCount--;
+                if (s_keyHandlerCount == 0 && s_deferredEnableShortcut)
+                {
+                    KeyboardShortcutManager.DisableShortcuts(false);//shortcuts enabled
+                    s_deferredEnableShortcut = false;
+                }             
+
```
Comment (hanzhang54) [inline src/Calculator/Common/KeyboardShortcuManager.cs:728]: Please remove the extra empty line.

File: src/Calculator/Common/KeyboardShortcuManager.cs [hunk 5]
```diff
@@ -831,6 +857,10 @@ private static void OnAcceleratorKeyActivated(CoreDispatcher dispatcher, Acceler
 
             //private static Concurrency.reader_writer_lock s_keyboardShortcutMapLock;
             private static readonly object s_keyboardShortcutMapLockMutex = new object();
+
+
```
Comment (hanzhang54) [inline src/Calculator/Common/KeyboardShortcuManager.cs:861]: Please remove the extra empty line.

File: src/Calculator/Common/KeyboardShortcuManager.cs [hunk 6]
```diff
@@ -714,6 +717,29 @@ private static void OnKeyDownHandler(CoreWindow sender, KeyEventArgs args)
...
+                s_keyHandlerCount--;
+                if (s_keyHandlerCount == 0 && s_deferredEnableShortcut)
+                {
+                    KeyboardShortcutManager.DisableShortcuts(false);//shortcuts enabled
+                    s_deferredEnableShortcut = false;
+                }             
+
+            }
+
+            public static void TryEnableShortcut()
```
Comment (hanzhang54) [inline src/Calculator/Common/KeyboardShortcuManager.cs:731]: We already have `DisableShortcuts()` to disable shortcuts and `HonorShortcuts()` to enable shortcuts. The 's_fDisableShortcuts' decides the value of `s_fHonorShortcuts` when it is set. Creating another `TryEnableShortcut()` is kind of confusing.

`DisableShortcuts()` is only used when the mode property is changed. We can keep using the `DisableShortcuts()` there and add the checking of `s_keyHandlerCount` in this method.

File: src/Calculator/Common/KeyboardShortcuManager.cs [hunk 7]
```diff
@@ -831,6 +857,10 @@ private static void OnAcceleratorKeyActivated(CoreDispatcher dispatcher, Acceler
 
             //private static Concurrency.reader_writer_lock s_keyboardShortcutMapLock;
             private static readonly object s_keyboardShortcutMapLockMutex = new object();
+
+
+            private static int s_keyHandlerCount;
```
Comment (hanzhang54) [inline src/Calculator/Common/KeyboardShortcuManager.cs:862]: Please initialize with the default value.

File: src/Calculator/Common/KeyboardShortcuManager.cs [hunk 8]
```diff
@@ -714,6 +717,29 @@ private static void OnKeyDownHandler(CoreWindow sender, KeyEventArgs args)
                 }
             }
 
+            private static void OnKeyUpHandler(CoreWindow sender, KeyEventArgs args)
+            {
+                s_keyHandlerCount--;
+                if (s_keyHandlerCount == 0 && s_deferredEnableShortcut)
+                {
+                    KeyboardShortcutManager.DisableShortcuts(false);//shortcuts enabled
```
Comment (hanzhang54) [inline src/Calculator/Common/KeyboardShortcuManager.cs:725]: `KeyboardShortcutManager` is not necessary here.

**Comment by hanzhang54** [comment]
Hi @jbaylon3, would you like to continue work on this PR? We plan to rename the master branch to main, could you please resolve those comments if possible? Thanks.

**Comment by jbaylon3** [comment]
> Hi @jbaylon3, would you like to continue work on this PR? We plan to rename the master branch to main, could you please resolve those comments if possible? Thanks.

File: src/Calculator/Common/KeyboardShortcuManager.cs [hunk 9]
```diff
@@ -322,14 +323,20 @@ public static void HonorShortcuts(bool allow)
 
             public static void DisableShortcuts(bool disable)
             {
-                int viewId = Utilities.GetWindowId();
-
-                if (s_fDisableShortcuts.ContainsKey(viewId))
+                //deferredEnableShortcut is being used to prevent the mode change from happening before the user input has processed 
+                if (s_keyHandlerCount > && !disable)
```
Comment (hanzhang54) [inline src/Calculator/Common/KeyboardShortcuManager.cs:327]: Please make it clear as `s_keyHandlerCount > 0`.

**Comment by hanzhang54** [comment]
@jbaylon3 I have one more comment and others look good to me. Also, please resolve the conflict with master branch for the file name. Thanks!

**Review by hanzhang54 — APPROVED** [review]
Good work! Thanks for your fix. 😊

**Comment by jbaylon3** [comment]
No problem!
