### PR TITLE
Date difference: display the difference in days (only) when we aren't able to calculate the difference in days/weeks/months..

### LINKED ISSUE #554: Prevent Date Difference to display faulty results
**Describe the bug**

When `DateCalculationEngine::GetDateDifference` isn't able to correctly calculate the number of years, months, weeks, days between two dates, the function currently returns an incorrect result, as seen with #552 (which focuses on a specific calculation error).

In order to prevent any further bugs in the future, we must add a way to indicate that the function weren't able to calculate correctly the difference and modify the ViewModel to display instead the number of days (only) between the two dates.

Note: This proposal doesn't try to fix #552 (#553 does it already), but prevent all future similar bugs.

**Steps To Reproduce**
- Open Calculator
- Switch to date calculation mode
- Go to the difference between dates - mode
- Enter start-date 31st of July 2019
- Enter end-date 30th of December 2019 (might be 31th of December to cause the bug in a different time-zone)

**Expected behavior**

**Screenshots**
image
Left: faulty result displayed
Right: display the difference in days when we aren't able to calculate the difference in year/month/week/day

**Device and Application Information**
 - OS Build: 10.0.18362.0
 - Architecture: X64
 - Application Version: 10.1904.42.0
 - Region: en-US
 - Dev Version Installed: True

**Requested Assignment**
If possible, I would like to fix this.

### PR DESCRIPTION
**Pull request by rudyhuyn**
## Fixes #554 

Modify how the Calculator behaves when `DateCalculationEngine::GetDateDifference` isn't able to calculate correctly the number of years, months, weeks, days between two dates.

Instead of displaying an incorrect result, the UI will now display the difference in days (only). 

### Description of the changes:
- Add new constant `DateDifferenceUnknown`
- rename `TryGetDateDifference` to `TryGetDateDifference` and modify the prototype to return a boolean.
- when we aren't able to calculate correctly the result, return false
- Modify `DateCalculatorViewModel::OnInputsChanged()` to display the difference in Days (only) when we were not able to calculate the difference in days/weeks/months 

### How changes were validated:
Manually.
This diff can be test with the same repro as #552 (if still not fixed).

### CODE REVIEW

File: src/CalcViewModel/DateCalculatorViewModel.cpp [hunk 1]
```diff
@@ -159,14 +172,21 @@ void DateCalculatorViewModel::UpdateDisplayResult()
 {
     if (m_IsDateDiffMode)
     {
-        // Are to and from dates the same
-        if (m_dateDiffResultInDays.day == 0)
+        if (m_dateDiffResultInDays == DateDifferenceUnknown)
+        {
+            IsDiffInDays = false;
+            StrDateDiffResultInDays = L"";
+            StrDateDiffResult = L"";
```
Comment (EriWong) [inline src/CalcViewModel/DateCalculatorViewModel.cpp]: >L"" [](start = 32, length = 3)

I wasn't able to hit this case when playing around, but it's probably worth adding a "Date calculation failed" message.  A blank result can give the user the impression that something is going on when in fact, nothing is still running.

Comment (rudyhuyn) [reply src/CalcViewModel/DateCalculatorViewModel.cpp]: This case _should_ never happen but we still need to manage it (in case of a future diff breaks it).

I will change the string.
