### PR TITLE
Fix formatting issues with CurrencyConverter and some locales

### LINKED ISSUE #240: Currency converter displays an extra space with some locales
**Describe the bug**

An extra space is added at the end of the number with some locales and numbers:

image

**Steps To Reproduce**
- Change your OS language to French or Spanish
- Open the currency converter
- Type 1111111
- See that the 2 currencies display 2 spaces instead of one 

**Expected behavior**
- Display only one space

**Device and Application Information (please complete the following information):**
 - OS Build: 10.0.18348.0
 - Architecture: X64
 - Application Version: 10.1812.10048.0

### PR DESCRIPTION
**Pull request by rudyhuyn**
## Fixes #240 and #232 

The ViewModel wrongly assumed that non-breaking spaces were only used between the value and the symbol. It's not the case of all locales using non-breaking spaces as a thousand delimiter (French for example).

When it was the case, the function only replaced the first thousand delimiter found and kept the extra space at the end of the string, generating 2 issues:

- Extra space at the end: https://github.com/Microsoft/calculator/issues/240 
- Bad formatting of the number: https://github.com/Microsoft/calculator/issues/232

### Description of the changes:

Replace `currencyResult.find(L'\u00a0')` by a regex only removing spaces at the end of the string.

### Screenshots
Before:

image

After:

image

### CODE REVIEW

File: src/CalcViewModel/UnitConverterViewModel.cpp [hunk 1]
```diff
@@ -53,6 +53,8 @@ constexpr size_t SELECTED_TARGET_UNIT = 2;
 
 // x millisecond delay before we consider conversion to be final
 constexpr unsigned int CONVERSION_FINALIZED_DELAY_IN_MS = 1000;
+const wregex regexTrimSpacesStart = wregex(L"^\\s+");
```
Comment (jefgen) [inline src/CalcViewModel/UnitConverterViewModel.cpp]: A few thoughts: I think what is considered a whitespace character (the `\s`) by the std::wregex library depends on the current locale setting. So there might be some odd cases where `\u00a0` isn't consider whitespace character by the locale, yet shows up in the currency result.

Comment (rudyhuyn) [reply src/CalcViewModel/UnitConverterViewModel.cpp]: I had a doubt too, but it should be fine. If no flags are passed in the constructor, the wregex will use ECMA and based on the spec, `\s` will always match `\u00a0`.

Spec here:
http://ecma-international.org/ecma-262/5.1/#sec-7.2

Comment (jefgen) [reply src/CalcViewModel/UnitConverterViewModel.cpp]: Nice! Thanks for the reply.

I suppose the problem might be if locales start using Narrow No-break Space (U+202F) at some point.
See the "Migration" section in CLDR v34 here: http://cldr.unicode.org/index/downloads/cldr-34

However, we currently override this in the CLDR data used by NLS in Windows, so that won't be an issue for now...

Comment (jefgen) [reply src/CalcViewModel/UnitConverterViewModel.cpp]: Actually, upon second reading of the ECMAScript spec:

> ECMAScript implementations must recognise all of the white space characters defined in Unicode 3.0. Later editions of the Unicode Standard may define other white space characters. ECMAScript implementations may recognise white space characters from later editions of the Unicode Standard.

U+202F `NARROW NO-BREAK SPACE` was added in Unicode 3.0.0, and is a Space (Zs) category. So I guess this *should* work for U+202F as well.

**Comment by jefgen** [comment]
Thanks @rudyhuyn :+1:

File: src/CalcViewModel/UnitConverterViewModel.cpp (hunk 1 above)
Comment (HowardWolosky) [reply src/CalcViewModel/UnitConverterViewModel.cpp]: Thanks for this thorough and thoughtful review, @jefgen.  Much appreciated.

**Comment by HowardWolosky** [comment]
Closing and re-opening to try and fix the PR build.

**Comment by HowardWolosky** [comment]
@mcooley - Something odd is going on with the CI pipeline here.  Any chance you can take a look?
