### PR TITLE
Unit Converter - Calculate the rounding precision of results based on the source

### LINKED ISSUE #455: Converter should progressively increase the number of significant digits (instead of switching from 7 to 15 instantly)
**Describe the improvement**
Based on the length of the string associated to the entry value, the converter will switch from 7 to 15 significant digits when the entry value length is higher than 7.

**Steps To Reproduce**
- Open the Length converter
- Select `centimeters` and `inches`
- Type `1.22222` in the centimeter field
- add 1 extra `2`
The result will switch from `0.481189` to `0.48118976377953`

**Expected behavior**
- based on the length of the entry value, we should progressively increase the number of significant digits, but not an instant switch.

**Screenshots**

**Current behavior:**

**Proposal:**

**Device and Application Information**
 - OS Build: 10.0.18362.0
 - Architecture: X64
 - Application Version: 10.1903.21.0
 - Region: en-US
 - Dev Version Installed: True

**Additional context**

The diff will also fix https://github.com/Microsoft/calculator/issues/416 at the same time.

### PR DESCRIPTION
**Pull request by rudyhuyn**
### Description of the changes:
- Ignore trailing zeros (issue #416), negative sign, decimal separator of the source when calculating the precision of the result 
- Round the result number based on the number of digits in the source value

### How changes were validated:
Manually tested, including the 2 repros from #455 and #416

### CODE REVIEW

File: src/CalcManager/UnitConverter.cpp [hunk 1]
```diff
@@ -879,16 +879,26 @@ void UnitConverter::Calculate()
         else
         {
             returnValue = stod(m_returnDisplay);
-            wstring returnString;
-            if (m_currentDisplay.size() <= OPTIMALDIGITSALLOWED && abs(returnValue) >= OPTIMALDECIMALALLOWED)
+
+            auto currentDisplayTrimmed = m_currentDisplay;
+            TrimString(currentDisplayTrimmed);
+            int currentNumberSignificantDigits = static_cast<int>(currentDisplayTrimmed.size());
+            if (currentDisplayTrimmed.find(L'.') != currentDisplayTrimmed.npos)
```
Comment (joseartrivera) [inline src/CalcManager/UnitConverter.cpp]: Doesn't the '.' character change based on the display language or does that happen later?

File: src/CalcManager/UnitConverter.cpp [hunk 2]
```diff
@@ -879,16 +879,26 @@ void UnitConverter::Calculate()
...
+                precision = MAXIMUMDIGITSALLOWED;
             }
             else
             {
-                returnString = RoundSignificant(returnValue, MAXIMUMDIGITSALLOWED - min(numPreDecimal, MAXIMUMDIGITSALLOWED));
+                precision = max(0, max(OPTIMALDIGITSALLOWED, min(MAXIMUMDIGITSALLOWED, currentNumberSignificantDigits)) - numPreDecimal);
             }
-            m_returnDisplay = returnString;
+       
+            m_returnDisplay = RoundSignificant(returnValue, precision);
```
Comment (joseartrivera) [inline src/CalcManager/UnitConverter.cpp]: Is this the expected behavior in currency mode? I would think we would at least always want a precision of 2 in that mode? Left is after this change, right is before. 

image

Comment (rudyhuyn) [reply src/CalcManager/UnitConverter.cpp]: You are right, for currency, I will force the display of X decimals based on the system locale settings (while waiting for the Calculator to include the number of digit to use per currency, see https://github.com/microsoft/calculator/issues/424#issuecomment-479823338)

File: src/CalcManager/UnitConverter.cpp (hunk 1 above)
Comment (rudyhuyn) [reply src/CalcManager/UnitConverter.cpp]: This is safe, this string is locale-independent

File: src/CalcManager/UnitConverter.cpp [hunk 3]
```diff
@@ -900,9 +901,9 @@ void UnitConverter::Calculate()
 /// Trims out any trailing zeros or decimals in the given input string
 /// </summary>
 /// <param name="input">wstring to trim</param>
-void UnitConverter::TrimString(wstring& returnString)
+void UnitConverter::TrimString(_Inout_ wstring& returnString)
 {
-    if (returnString.find(L'.') == m_returnDisplay.npos)
```
Comment (rudyhuyn) [inline src/CalcManager/UnitConverter.cpp]: Bug fixed!

Comment (danbelcher-MSFT) [reply src/CalcManager/UnitConverter.cpp]: What was the bug?  [`npos`](https://en.cppreference.com/w/cpp/string/basic_string/npos) is a static member of `basic_string`.  My understanding is that the condition should be `returnString.find(L'.') == wstring::npos`.  You can write `m_returnDisplay.npos` or `returnString.npos`, but I believe it should be the same either way because they are referring to the same static member.  We should still prefer `wstring::npos` because it makes it clear that the member is static instead of the current form which implies non-static.

File: src/CalcManager/UnitConverter.cpp [hunk 4]
```diff
@@ -922,6 +923,24 @@ void UnitConverter::TrimString(wstring& returnString)
...
 }
 
+/// <summary>
+/// Get number of significant digits (integer part + fractional part) of a number</summary>
+/// <param name="value">the number</param>
+unsigned int UnitConverter::GetNumberSignificantDigits(std::wstring value)
+{
+    TrimString(value);
+    unsigned int numberSignificantDigits = static_cast<unsigned int>(value.size());
+    if (value.find(L'.') != value.npos)
```
Comment (danbelcher-MSFT) [inline src/CalcManager/UnitConverter.cpp]: Same comment here and below.  My understanding is this should be `wstring::npos`

File: src/CalcManager/UnitConverter.h [hunk 5]
```diff
@@ -292,6 +290,10 @@ namespace UnitConversionManager
         std::shared_ptr<IConverterDataLoader> GetDataLoaderForCategory(const Category& category);
         std::shared_ptr<ICurrencyConverterDataLoader> GetCurrencyConverterDataLoader();
 
+        static void TrimString(_Inout_ std::wstring& input);
```
Comment (danbelcher-MSFT) [inline src/CalcManager/UnitConverter.h]: Are these functions specific to UnitConverter?  Would it make more sense to put them as free functions in Utils?

File: src/CalcManager/UnitConverter.cpp [hunk 6]
```diff
@@ -922,6 +923,24 @@ void UnitConverter::TrimString(wstring& returnString)
     }
 }
 
+/// <summary>
+/// Get number of significant digits (integer part + fractional part) of a number</summary>
+/// <param name="value">the number</param>
+unsigned int UnitConverter::GetNumberSignificantDigits(std::wstring value)
+{
+    TrimString(value);
+    unsigned int numberSignificantDigits = static_cast<unsigned int>(value.size());
```
Comment (danbelcher-MSFT) [inline src/CalcManager/UnitConverter.cpp]: What's wrong with `size_t`?  :)

Comment (rudyhuyn) [reply src/CalcManager/UnitConverter.cpp]: The function returns a unsigned int, so a cast is necessary.

Comment (rudyhuyn) [reply src/CalcManager/UnitConverter.cpp]: The function returns an unsigned int, so a cast is necessary.

Comment (danbelcher-MSFT) [reply src/CalcManager/UnitConverter.cpp]: I was mostly poking for fun :)  Although, if the return value is derived from a type with a higher precision there's no imperative to convert to a lower precision type.  It would indicate to me that the return type should also be `size_t`.  That said, I'm not sure how many clients there are of this function and maybe you didn't want to go update.

File: src/CalcManager/UnitConverter.h (hunk 5 above)
Comment (rudyhuyn) [reply src/CalcManager/UnitConverter.h]: Not specific but only used by UnitConverter.

There is no way to make a free-standing function private, so I would prefer to not do it, especially with this library which has a high chance of being used by other projects. 

- free-standing in global namespace -> can create collision when another app uses this library
- free-standing in namespace -> still visible
- utility class -> better to avoid.

There is probably some functions (including from other classes) we can group to create a new class that will make more sense (`NumberStringOperation`?), but it can be part of another PR.

For this diff, I hesitated to remove these functions from the header file and only keep the implementation, do you have a guidance/best practice for that?

File: src/CalcManager/UnitConverter.cpp (hunk 3 above)
Comment (rudyhuyn) [reply src/CalcManager/UnitConverter.cpp]: The bug wasn't technical but logical, it was weird to use an instance we don't even use in this function to get access to npos.

All methods in this class get access to `wstring::npos` via instances, I was intrigued but I thought it was made on purpose for a reason I ignored. But it looks like it's the only class doing that, so I'm totally fine with using wstring:npos instead!

File: src/CalcManager/UnitConverter.h (hunk 5 above)
Comment (danbelcher-MSFT) [reply src/CalcManager/UnitConverter.h]: I don't see a problem with having the functions be visible to other projects.  We _want_ them to be visible so that they can be reused.  If the functions don't have anything specific to UnitConverter, then it doesn't make sense to tie them to the UnitConverter class.  If they were free functions we would still do our due diligence and put them in an appropriate namespace.  Like many of my comments, I'm not necessarily asking for a change here, but I find the discussion valuable.  In this case, I don't see the concern with string manipulation functions being free and grouped under an appropriate namespace.

Regarding your last comment, you wanted to remove the functions from the header file and only keep the implementation..  did you mean remove them as static members of UnitConverter and keep the definitions in the source file?  I don't have a problem with that, although I would have the same question of whether it was more appropriate to move them to a common namespace/class.  If you were to make that change, please place the definitions in an anonymous namespace.  One reason to keep the functions as private static members would be so that they can be unit tested.

Comment (rudyhuyn) [reply src/CalcManager/UnitConverter.h]: > I don't see a problem with having the functions be visible to other projects.

In this case, we are fine, it was my main concern. I will update the PR.

For the namespace (unfortunately CalcManager does not have a clean namespace structure) what do you think about `CalculationManager::StringUtils`

Comment (danbelcher-MSFT) [reply src/CalcManager/UnitConverter.h]: Thanks, @rudyhuyn!  `CalcManager` would also be fine.  It matches the project name and we abbreviate elsewhere  as with `CalcViewModel`.  Either way, adding namespaces for the CalcManager project is much appreciated.

**Comment by grochocki** [comment]
ping: @joseartrivera

File: src/CalcManager/UnitConverter.cpp [hunk 7]
```diff
@@ -842,100 +844,59 @@ void UnitConverter::Calculate()
...
-                returnString = RoundSignificant(returnValue, MAXIMUMDIGITSALLOWED - min(numPreDecimal, MAXIMUMDIGITSALLOWED));
+                int currentNumberSignificantDigits = GetNumberDigits(m_currentDisplay);
+                int precision = 0;
+                if (abs(returnValue) < OPTIMALDECIMALALLOWED)
+                {
+                    precision = MAXIMUMDIGITSALLOWED;
+                }
+                else
+                {
+                    precision = max(0, max(OPTIMALDIGITSALLOWED, min(MAXIMUMDIGITSALLOWED, currentNumberSignificantDigits)) - numPreDecimal);
```
Comment (joseartrivera) [inline src/CalcManager/UnitConverter.cpp]: I think this makes sense, can we add a small comment giving an explanation for the logic here?

**Comment by rudyhuyn** [comment]
> Hi Rudy, sorry for the delay on my response. Just a few small requests before merging this in. Thanks again for taking on this work! :)

all done!
