### PR TITLE
Fix the focus when right-clicking CalculationResult's TextBlock

### LINKED ISSUE #642: Right-click on numbers fails to highlight after 'selecting all' from context menu
**Describe the bug**
When trying to "select all" when right-clicking on the main display output, you are not able to actually select all text.

**Steps To Reproduce**
1. Enter in a number in Calculator
2. Right-click on the number and click "select all"

**Expected behavior**
Display text appears selected.

**Screenshots**
Could not capture a good screenshot.

**Device and Application Information**
 - OS Build: 10.0.18942.0
 - Architecture: X64
 - Application Version: 10.1907.22.0
 - Region: en-US
 - Dev Version Installed: True

**Additional context**
Right-clicking again selects all text, so it appears this bug might only affect visuals.

**Requested Assignment**
I'm just reporting this problem.  I don't want to fix it.

### PR DESCRIPTION
**Pull request by praveensvsrk**
### Description of the changes:
- Focused the TextBlock element when the event source is the TextBlock itself. This fixes the resultant number not gaining focus when a right-click is performed.

### How changes were validated:

- Tested Manually

### CODE REVIEW

**Comment by rudyhuyn** [comment]
This change can prevent `CalculationResult::OnGotFocus` to be called, which means that the control can't update its visual state.

**BUT** this is not a problem because none of the CalculationResult templates used by the app contains a visual state called "Focused", so your change is perfect! 

I will submit another PR to remove `OnGotFocus` and `OnLostFocus`.

Good job!! 👍

File: src/Calculator/Controls/CalculationResult.cpp [hunk 1]
```diff
@@ -377,7 +377,16 @@ void CalculationResult::OnTapped(TappedRoutedEventArgs ^ e)
 
 void CalculationResult::OnRightTapped(RightTappedRoutedEventArgs ^ e)
 {
-    this->Focus(::FocusState::Programmatic);
+    auto requestedElement = e->OriginalSource;
+
+    if (requestedElement->Equals(safe_cast<Object ^>(m_textBlock)))
```
Comment (joseartrivera) [inline src/Calculator/Controls/CalculationResult.cpp]: use dynamic_cast instead since m_textBlock could technically be nullptr if a style is applied to this control that doesn't; include it.

Comment (praveensvsrk) [reply src/Calculator/Controls/CalculationResult.cpp]: Makes sense! I will do the change.
