### PR TITLE
CalcViewModel code cleaning

### LINKED ISSUE #753: CalcViewModel contains classes related to UI + dead codes.
**Describe the bug**
CalcViewModel contains many classes related to the UI that should be moved to the Calculator project.
- KeyboardShortcutManager
- ValidationConverter
- ViewState

And some dead codes:
- BindingBase
- UnitConverterViewModel::StartConversionResultTimer
- StandardCalculatorViewModel::ConvertIntegerToNumbersAndOperatorsEnum
- StandardCalculatorViewModel::OnPinUnpinCommand
- StandardCalculatorViewModel::SetViewPinnedState
- StandardCalculatorViewModel::KeyPressed
- StandardCalculatorViewModel::GetSelectedTokenType

In addition, CalcViewModel imports the NuGet Microsoft.UI.Xaml package that won't be required once the above methods/classes are removed.

**Requested Assignment**
If possible, I would like to fix this.

### PR DESCRIPTION
**Pull request by rudyhuyn**
### Description of the changes:
- move KeyboardShortcutManager, ValidationConverter and ViewState to Calculator
- remove dead code listed in #753 
- remove Microsoft.UI.Xaml nuget package from CalcViewModel

### How changes were validated:
- manually

### CODE REVIEW

File: src/Calculator/Common/AppLifecycleLogger.cpp [hunk 1]
```diff
@@ -3,7 +3,7 @@
 
 #include "pch.h"
 #include "AppLifecycleLogger.h"
-#include "CalcViewModel/Common/TraceActivity.h"
+#include <winmeta.h>
```
Comment (joshkoon) [inline src/Calculator/Common/AppLifecycleLogger.cpp]: Standard header - include in pch.h, instead?

**Comment by joshkoon** [comment]
Thanks for making these changes, @rudyhuyn !

**Comment by rudyhuyn** [comment]
git rebase done!
