### PR TITLE
Prevent the application to crash when the current page is Date Calculation and users paste a text

### LINKED ISSUE #389: The application crashes when users press ctrl+V while displaying the Date Calculation page.
**Describe the bug**
The application (including the public version) crashes when users press ctrl+V if the application only displayed the Date Calculation page during its lifecycle (application started with Date Calculation and no navigation happened). 

This bug only happens with Date Calculation, the only page not managing the clipboard.

**Steps To Reproduce**
- Copy a random text in your clipboard
- launch the app
- Select Date Calculation
- Close the app
- Launch the application again
- Press Ctrl+V (

**Expected behavior**
The application shouldn't crash

**Screenshots**

**Device and Application Information:**
 - OS Build: 10.0.18361.0
 - Architecture: X64
 - Application Version: 10.1812.10048.0

### PR DESCRIPTION
**Pull request by rudyhuyn**
### Description of the changes:
- Fix the else condition in ApplicationViewModel::OnPaste

### How changes were validated:
Manually

### CODE REVIEW

File: src/CalcViewModel/ApplicationViewModel.cpp [hunk 1]
```diff
@@ -189,7 +189,7 @@ void ApplicationViewModel::OnPasteCommand(Object^ parameter)
     {
         ConverterViewModel->OnPasteCommand(parameter);
     }
-    else
+    else  if(NavCategory::IsCalculatorViewMode(m_mode))
```
Comment (HowardWolosky) [inline src/CalcViewModel/ApplicationViewModel.cpp]: nit: spacing here is off

```suggestion
    else if (NavCategory::IsCalculatorViewMode(m_mode))
```

**Comment by HowardWolosky** [comment]
@rudyhuyn  - Just looking for a minor update to this, and then we can get it merged in.
Thanks!
