### PR TITLE
Restore user preferences

### LINKED ISSUE #445: User preferences are not restored between sessions.
**Describe the bug**
Looking at Calculator source code, it looks like we meant save a user's last selected category and units, and restore them when a calculator starts up. In other words, Calculator meant to support saving & restoring user preferences between sessions.
However, calculator is failing to restore saved units. It does restore saved category.

**Steps To Reproduce**
1. Launch Calculator.
2. Pick a category (ex> Area) and units (ex> Hectares to Acres )
3. Close & re-launch Calculator.

**Expected behavior**
A user's last selected category and units should be restored when a calculator starts up (i.e. if you chose category Area and unit Hectares to Acres, and restarts Calculator, then Calculator should show category Area and unit Hectares to Acres ).
However, Calculator reverts back to the default units ( it does seem to restore category though ). 

**Screenshots**
Please refer to [this video](https://www.dropbox.com/s/65bg4tlnde81ook/prefernces_demo.mp4?dl=0).

For quick reference, refer to the below
preferences_bug_demo

**Device and Application Information (please complete the following information):**
 - OS Build: 10.0.17763.0
 - Architecture: X64
 - Application Version: 10.1812.10048.0

**Additional context**
- `UnitConverter::RestoreUserPreferences()` is working correctly.
- `UnitConverter::SaveUserPreferences()` is working correctly.
- However, after restoring saved values on Calculator startup, Something is overriding the restored value to the default value.

_Note: I would like to tackle this one and make a PR 🙂 if this issue gets accepted._

### PR DESCRIPTION
**Pull request by TurtleShip**
### Description of the changes:
**1) Do not set units to default values if they already have valid values** 
This fixes the actual issue. `UnitConverter::InitializeSelectedUnits()` ( this function resets all units to their default units if available for the current category ) gets called after `UnitConverterViewModel::RestoreUserPreferences()` ( this function restores user preferences ).
So Calculator has been restoring saved values, and then overriding the restored values with default values.
I modified `InitializeSelectedUnits()` so that we only initialize units only when they are not already set to valid units for the current category.

**2) Removed `m_isFirstTime`** 
I noticed that we are calling `RestoreUserPreferences()`  twice  when Calculator starts up, and the function is restoring the same value both times

The below happens when Calculator starts up
1) On startup, in `UnitConverterViewModel::InitializeView()`, `RestoreUserPreferences()` is called.
2) `RestoreUserPreferences()` in turn triggers `OnUnitChanged()`
3) During the first call to `OnUnitChanged()`, m_IsFirstTime is `True`, so we call `RestoreUserPreferences()` again while also setting `m_IsFirstTime` to `False`. 
4) `RestoreUserPreference()` again triggers `OnUnitChanged()`
5) During the second call to `OnUnitChanged()`,  m_IsFirstTime is `False`, so we call `SaveUserPreferences()`

I think we should only call `SaveUserPreferences()` inside `OnUnitChanged()` since we already restored user preferences during view initialization. I can't really think of a reason to restore units after view has been initialized. This led me to just delete `m_isFirstTime`.

### How changes were validated:
Manually tested that units and the current category are properly selected when you quit and start Calculator.

GifMaker_20190414182150911

GifMaker_20190414183403644

### CODE REVIEW

File: src/CalcManager/UnitConverter.cpp [hunk 1]
```diff
@@ -922,17 +922,25 @@ void UnitConverter::InitializeSelectedUnits()
     vector<Unit> curUnits = itr->second;
     if (!curUnits.empty())
     {
+        bool isFromRestored = find(curUnits.begin(), curUnits.end(), m_fromType) != curUnits.end();
```
Comment (rudyhuyn) [inline src/CalcManager/UnitConverter.cpp]: NIT: `isFromUnitAvailable` would probably be easier to understand?

File: src/CalcManager/UnitConverter.cpp [hunk 2]
```diff
@@ -922,17 +922,25 @@ void UnitConverter::InitializeSelectedUnits()
...
+        bool isToRestored = find(curUnits.begin(), curUnits.end(), m_toType) != curUnits.end();
```
Comment (rudyhuyn) [inline src/CalcManager/UnitConverter.cpp]: NIT: rename `isFromUnitValid` and `isToUnitValid` + a comment explaining why we check them.

Comment (rudyhuyn) [reply src/CalcManager/UnitConverter.cpp]: small optimization: 
```
 bool isFromRestored = m_fromType == EMPTY_UNIT && find(curUnits.begin(), curUnits.end(), m_fromType) != curUnits.end();
```###

**Comment by rudyhuyn** [comment]
It really improves the user experience! I added 2 NIT comments, let me know what you think.
Thank you for taking care of that!

File: src/CalcManager/UnitConverter.cpp (hunk 2 above)
Comment (TurtleShip) [reply src/CalcManager/UnitConverter.cpp]: > NIT: rename `isFromUnitValid` and `isToUnitValid` + a comment explaining why we check them (units available for this region)

Thanks, @rudyhuyn !
I updated as suggested. Can you take a look at added comments please? I am afraid that you might have misunderstood why I was checking those values.

Comment (rudyhuyn) [reply src/CalcManager/UnitConverter.cpp]: The comment is right but another positive aspect of this check is that you will override units when they don't exist, many reasons possible:
- a unit was removed by a previous update (or moved to another category)
- the unit restored is not available for the current locale (user selected Pyeong, then changed region and started again the app)


-

Comment (TurtleShip) [reply src/CalcManager/UnitConverter.cpp]: Ah,, makes sense!
As for the second case, it shouldn't happen once #444 lands since the PR won't allow restoring values that aren't valid for the current locale in the first place.

**Comment by TurtleShip** [comment]
Hi, gentle bump on this.
It looks like I need a review from a reviewer with write access.
Could such a reviewer take a look please?

Thanks!

**Comment by HowardWolosky** [comment]
Sorry for the delay, @TurtleShip.  I am looking at this, but I'm also looking through the archived history of the code around this.  The code wasn't exactly this way when it was initially written, and so I'm trying to review the history to see if there were other bugs/cases that were trying to be corrected along the way that we'd be regressing by taking this change.  I should have feedback on this PR next week.  Thanks for your patience.

**Comment by TurtleShip** [comment]
Hi, @HowardWolosky 
I was wondering if you have updates on this 🙂

**Comment by HowardWolosky** [comment]
>Hi, @HowardWolosky Howard Wolosky FTE
>I was wondering if you have updates on this 🙂

Hey there -- apologies for the delay.  Preparation for this year's BUILD conference took up a bit more time than anticipated.  I should have my investigation into the history around this code completed this week.  I appreciate your continued patience here.

**Comment by TurtleShip** [comment]
Hi, a gentle bump on this... 🙂

**Comment by HowardWolosky** [comment]
You're totally right on this @TurtleShip -- I apologize for the delay and radio silence here.  Other things came up preventing me from finishing that investigation.  I'll be prioritizing this soon and hope that we can get this merged in within the next two weeks.  I apologize again and appreciate your patience here.

File: src/CalcViewModel/UnitConverterViewModel.cpp [hunk 3]
```diff
@@ -147,15 +147,13 @@ UnitConverterViewModel::UnitConverterViewModel(const shared_ptr<UCM::IUnitConver
...
 
-    m_IsFirstTime = true;
     m_model->Initialize();
     PopulateData();
 }
 
 void UnitConverterViewModel::ResetView()
 {
     m_model->SendCommand(UCM::Command::Reset);
-    m_IsFirstTime = true;
```
[the remark this answers is not in the document]
Comment (TurtleShip) [reply src/CalcViewModel/UnitConverterViewModel.cpp]: Done :)

**Comment by TurtleShip** [comment]
Hi, @HowardWolosky 

I've addressed your comments.
Thanks for taking time to look at my PR and I look forward to see it being merged to the master!
😄

**Comment by rudyhuyn** [comment]
Good job Seulgi!
