### PR TITLE
Fix crash when tabbing through KGF

### LINKED ISSUE #1033: Tabbing through Key Graph Features with Narrator on causes crash
**Describe the bug**
Tabbing through Key Graph Features with Narrator on causes crash

**Steps To Reproduce**
1. Graph an equation
2. Open narrator
3. Click analysis
4. Tab through the analysis screen

**Expected behavior**
Doesn't crash

### PR DESCRIPTION
**Pull request by joseartrivera**
### Description of the changes:
- Check if textbox is read only before trying to submit an equation on focus lost

### How changes were validated:
- Manual test

### CODE REVIEW

File: src/Calculator/Controls/MathRichEditBox.cpp [hunk 1]
```diff
@@ -111,7 +111,10 @@ void MathRichEditBox::SetMathTextProperty(String ^ newValue)
 
 void CalculatorApp::Controls::MathRichEditBox::OnLosingFocus(Windows::UI::Xaml::UIElement ^ sender, Windows::UI::Xaml::Input::LosingFocusEventArgs ^ args)
 {
-    SubmitEquation(EquationSubmissionSource::FOCUS_LOST);
+    if (!IsReadOnly)
```
Comment (rudyhuyn) [inline src/Calculator/Controls/MathRichEditBox.cpp]:
```suggestion
    if (this->!IsReadOnly)
```
