### PR TITLE
Use different formatter for different currency

### LINKED ISSUE #424: Application fails to take float value for Currency converter when Japanese Calendar is enabled
A team member will update this issue with more details soon.

### PR DESCRIPTION
**Pull request by xuhongxu96**
## Fixes #424 , #1204 , #1438  .

Before, the Calculator will use `CurrencyFormatter` per system locale for all currencies.
So, users cannot input `USD` with fraction digits in Japanese locale, because `JPY` doesn't allow fraction digits.

### Description of the changes:
- Allow to use different formatter for different currency
   - By adding `m_currencyFormatter1`, `m_currencyFormatter2`

### How changes were validated:

- <del>Functional UI tests</del> (it does not work because there is no full currency list in CI)
- Add unit test case `TestCurrencyFormattingLogic` for `UnitConverterViewModel`

### CODE REVIEW

**Comment by xuhongxu96** [comment]
Seems I cannot add currency functional test because it only has "Jupiter - Gas Money" in ComboBox in CI

**Comment by xuhongxu96** [comment]
Seems I cannot add currency functional test because it only has a fake currency in CI.
Any suggestions?

**Comment by xuhongxu96** [comment]
Seems in CI the Calculator doesn't have full currency list?

File: src/CalcViewModel/UnitConverterViewModel.cpp [hunk 1]
```diff
@@ -312,18 +338,18 @@ String ^ UnitConverterViewModel::ConvertToLocalizedString(const std::wstring& st
...
             m_decimalFormatter->FractionDigits = static_cast<int>(stringToLocalize.length() - (posOfDecimal + 1));
-            m_currencyFormatter->FractionDigits = m_currencyMaxFractionDigits;
+            currencyFormatter->FractionDigits = lastCurrencyFractionDigits;
         }
 
         if (IsCurrencyCurrentCategory)
         {
-            wstring currencyResult = m_currencyFormatter->Format(stod(stringToLocalize))->Data();
-            wstring currencyCode = m_currencyFormatter->Currency->Data();
+            wstring currencyResult = currencyFormatter->Format(stod(stringToLocalize))->Data();
```
Comment (joseartrivera) [inline src/CalcViewModel/UnitConverterViewModel.cpp:351]: This results in the conversions to Yen from other currencies always displaying a decimal, is this existing behavior?

image

File: src/CalcViewModel/UnitConverterViewModel.cpp [hunk 2]
```diff
@@ -280,10 +282,33 @@ String ^ UnitConverterViewModel::ConvertToLocalizedString(const std::wstring& st
         return result;
     }
 
+    CurrencyFormatter ^ currencyFormatter;
+
+    switch (cfp)
+    {
+    case CurrencyFormatterParameter::Default:
```
Comment (joseartrivera) [inline src/CalcViewModel/UnitConverterViewModel.cpp:289]: Might be better to just make this the 'default:' case

File: src/CalcViewModel/UnitConverterViewModel.cpp [hunk 3]
```diff
@@ -803,10 +833,26 @@ void UnitConverterViewModel::UpdateInputBlocked(_In_ const wstring& currencyInpu
     m_isInputBlocked = false;
     if (posOfDecimal != wstring::npos && IsCurrencyCurrentCategory)
     {
-        m_isInputBlocked = (posOfDecimal + static_cast<size_t>(m_currencyMaxFractionDigits) + 1 == currencyInput.length());
+        m_isInputBlocked = (posOfDecimal + static_cast<size_t>(CurrencyFormatterFrom->FractionDigits) + 1 == currencyInput.length());
     }
 }
 
+void UnitConverterViewModel::UpdateCurrencyFormatter()
```
Comment (joseartrivera) [inline src/CalcViewModel/UnitConverterViewModel.cpp:840]: Should we disable the '.' keyboard key in the case of yen too?

**Review by joseartrivera — CHANGES_REQUESTED** [review]
Thanks for the fix! This seems to be working great, just a few questions to answer, let me know what you think.

File: src/CalcViewModel/UnitConverterViewModel.cpp (hunk 1 above)
Comment (xuhongxu96) [reply src/CalcViewModel/UnitConverterViewModel.cpp:351]: It's an existing behavior. If you change locale to Japanese, all currency converted to will have a decimal:
image

But I think we can discuss about this -- is it really needed?

File: src/CalcViewModel/UnitConverterViewModel.cpp (hunk 2 above)
Comment (xuhongxu96) [reply src/CalcViewModel/UnitConverterViewModel.cpp:289]: Sure.

File: src/CalcViewModel/UnitConverterViewModel.cpp (hunk 3 above)
Comment (xuhongxu96) [reply src/CalcViewModel/UnitConverterViewModel.cpp:840]: I think this question is related to the first one -- Shall we keep the trailing decimal?
If we decided to show the trailing decimal, it would be weird to disable the '.' key.

File: src/CalcViewModel/UnitConverterViewModel.cpp (hunk 1 above)
Comment (joseartrivera) [reply src/CalcViewModel/UnitConverterViewModel.cpp:351]: I don't think it's needed, would be great if it is easy to remove!

File: src/CalcViewModel/UnitConverterViewModel.cpp (hunk 3 above)
Comment (joseartrivera) [reply src/CalcViewModel/UnitConverterViewModel.cpp:840]: I am fine with keeping the existing behavior

File: src/CalcViewModel/UnitConverterViewModel.cpp (hunk 1 above)
Comment (xuhongxu96) [reply src/CalcViewModel/UnitConverterViewModel.cpp:351]: Should be easy. Let me do it together with disabling decimal input.

File: src/CalcManager/UnitConverter.cpp [hunk 4]
```diff
@@ -191,6 +191,11 @@ void UnitConverter::SwitchActive(const wstring& newValue)
     }
 }
 
+bool UnitConversionManager::UnitConverter::IsSwitchedActive() const
+{
+    return m_switchedActive;
+}
+
```
Comment (xuhongxu96) [inline src/CalcManager/UnitConverter.cpp:198]: Before, after user switches active and then changes the currency unit, the input may be blocked.
This is because the unit changed to has less fraction digits than the previous unit.

However, as the new value will always replace the old value after switched active, user should be able to input regardless of the old value. 

So, I have to add this method so that `ViewModel` can decide whether to block the input per `switchedActive`.

File: src/CalcViewModel/UnitConverterViewModel.cpp [hunk 5]
```diff
@@ -473,14 +504,12 @@ void UnitConverterViewModel::OnButtonPressed(Platform::Object ^ parameter)
...
-	{
-		return;
-	}
-	m_model->SendCommand(command);
+                                                 UCM::Command::Five, UCM::Command::Six, UCM::Command::Seven, UCM::Command::Eight, UCM::Command::Nine };
+    if (m_isInputBlocked && !m_model->IsSwitchedActive() && command != UCM::Command::Clear && command != UCM::Command::Backspace)
+    {
+        return;
+    }
+    m_model->SendCommand(command);
```
Comment (xuhongxu96) [inline src/CalcViewModel/UnitConverterViewModel.cpp:512]: `!m_model->IsSwitchedActive()` means input is allowed as long as user just switches active.

File: src/CalcManager/UnitConverter.cpp (hunk 4 above)
Comment (xuhongxu96) [reply src/CalcManager/UnitConverter.cpp:198]: I think we'd better add some real currency data (only abbr. matters, the rates can be fake) in UI Tests.
Otherwise, we cannot easily test the case mentioned here.

File: src/CalcViewModel/UnitConverterViewModel.cpp (hunk 5 above)
Comment (xuhongxu96) [reply src/CalcViewModel/UnitConverterViewModel.cpp:512]: I've added the same comment in code.

File: src/CalcManager/UnitConverter.cpp (hunk 4 above)
Comment (xuhongxu96) [reply src/CalcManager/UnitConverter.cpp:198]: @joseartrivera As the test data is discussed in another issue thread, maybe we can do it in another PR. Let's skip it for now?

File: src/CalculatorUITestFramework/UnitConverterPage.cs [hunk 6]
```diff
@@ -64,5 +64,44 @@ public void EnsureCalculatorIsCurrencyMode()
...
+            CalculatorApp.ClickOnWindow();
+            UnitConverterOperators.Units1.SendKeys(OpenQA.Selenium.Keys.Home);
+            UnitConverterOperators.Units1.SendKeys(OpenQA.Selenium.Keys.Enter);
+
+            CalculatorApp.ClickOnWindow();
+            UnitConverterOperators.Units2.SendKeys(OpenQA.Selenium.Keys.Home);
+            UnitConverterOperators.Units2.SendKeys(OpenQA.Selenium.Keys.Enter);
+
+            CalculatorApp.ClickOnWindow();
+        }
```
Comment (xuhongxu96) [inline src/CalculatorUITestFramework/UnitConverterPage.cs:81]: Should fix #1438

File: src/CalcViewModel/UnitConverterViewModel.cpp [hunk 7]
```diff
@@ -293,7 +319,8 @@ String ^ UnitConverterViewModel::ConvertToLocalizedString(const std::wstring& st
         std::wstring significandStr(stringToLocalize.substr(0, posOfE));
         std::wstring exponentStr(stringToLocalize.substr(posOfSign + 1, stringToLocalize.length() - posOfSign));
 
-        result += ConvertToLocalizedString(significandStr, allowPartialStrings) + "e" + signOfE + ConvertToLocalizedString(exponentStr, allowPartialStrings);
+        result += ConvertToLocalizedString(significandStr, allowPartialStrings, cfp) + "e" + signOfE
```
Comment (joseartrivera) [inline src/CalcViewModel/UnitConverterViewModel.cpp:322]: There is a bug when testing with a currency without fractional digits, I get two different answers in this circumstance:

1. Switch first currency to "Test Fractional Digits"
2. Switch second currency to "Test Fractional Digits"
3. In the first currency input, type 1.999
4. Switch the first currency to "Test No Fractional Digits" 
5. Notice the conversion says 2 -> 399.800, even though the conversion rate is 1 = 200.00
6. Hit the CE buton, type 2 in manually, notice the answer is now 2 -> 400.

I think the issue is that we display how the currency is formatted and displayed but we don't use that value in the actual calculation.

**Review by joseartrivera — CHANGES_REQUESTED** [review]

File: src/CalcViewModel/UnitConverterViewModel.cpp (hunk 7 above)
Comment (xuhongxu96) [reply src/CalcViewModel/UnitConverterViewModel.cpp:322]: Wow, thanks for your finding! 
Seems that I have to truncate the digits after switching the currency, which means the digits will be gone forever even if I switch back.

Comment (xuhongxu96) [reply src/CalcViewModel/UnitConverterViewModel.cpp:322]: Fixed and added a UI test case.

File: src/CalculatorUITests/CurrencyConverterFunctionalTests.cs [hunk 8]
```diff
@@ -256,6 +257,45 @@ public void MouseInput_SwitchCurrencyWithLessFractionalDigitsAndEnterInput()
...
+            page.UnitConverterOperators.ClearButton.Click();
+
+            page.UnitConverterOperators.NumberPad.Num2Button.Click();
+            page.UnitConverterOperators.NumberPad.Num0Button.Click();
+            page.UnitConverterOperators.NumberPad.Num0Button.Click();
+
+            Assert.AreEqual("200", page.UnitConverterResults.GetCalculationResult1Text());
+            Assert.AreEqual(result, page.UnitConverterResults.GetCalculationResult2Text());
+        }
+
```
Comment (xuhongxu96) [inline src/CalculatorUITests/CurrencyConverterFunctionalTests.cs:298]: Added a UI test case for the bug you found

**Review by joseartrivera — APPROVED** [review]
Works great, thanks again for the fix!
