### PR TITLE
Fix bug when the negate sign is before a space 

### LINKED ISSUE #294: minus a negative number isn't interpreted correctly in scientific mode
**Describe the bug**
Calculator computes sums such as (4 - -4) incorrectly in scientific mode [where I expect it to understand complex sums properly]

**Steps To Reproduce**
1. Set scientific mode
1. Type `(4 - -4)` into notepad copy-paste it into calculator.

**Expected behavior**
Calculator shows that it parsed `(4 - -4)` as `(4 + 4) or other equivalent e.g.  `(4 - (-4))`, `(4 - (0 - 4))` etc.

**Actual behavior**
Calculator shows that it parsed `(4 - -4)` as `(4 - 4)` which we all know is not mathematically the same!

**Device and Application Information (please complete the following information):**
 - OS Build: 18342.8
 - Architecture: x64
 - Application Version: 10.1812.10048.0

### PR DESCRIPTION
**Pull request by rudyhuyn**
### Description of the changes:
Ignore `None` characters while parsing the clipboard, so '4-<space>-6' would be correctly interpreted.

The issue was that `isPreviousOperator` was set to `False`because of the space character, ignore it solve the issue. 

### How changes were validated:
- tested with different values

### CODE REVIEW

File: src/CalcViewModel/StandardCalculatorViewModel.cpp [hunk 1]
```diff
@@ -1430,29 +1433,29 @@ void StandardCalculatorViewModel::SaveEditedCommand(_In_ unsigned int tokenPosit
...
+                                updatedToken = CCalcEngine::OpCodeToUnaryString(static_cast<int>(Command::CommandCOSH), true, angleType);
+                                break;
+                                case static_cast<int>(Command::CommandATANH) :
+                                    updatedToken = CCalcEngine::OpCodeToUnaryString(static_cast<int>(Command::CommandTANH), true, angleType);
+                                    break;
+                                    case static_cast<int>(Command::CommandPOWE) :
+                                        updatedToken = CCalcEngine::OpCodeToUnaryString(static_cast<int>(Command::CommandLN), true, angleType);
+                                        break;
+                                    default:
+                                        updatedToken = CCalcEngine::OpCodeToUnaryString(nOpCode, false, angleType);
```
Comment (mauve) [inline src/CalcViewModel/StandardCalculatorViewModel.cpp]: something screwed up the indentation of this switch-case

**Comment by joseartrivera** [comment]
Hey @rudyhuyn I signed off on this, but could you fix the formatting before I merge it in?

Thanks!
