### PR TITLE
Fix graphing crash when plotting equations with errors

### LINKED ISSUE #957: Graphing mode crashes on some equations that contain errors
**Describe the bug**
Graphing mode crashes on some equations that contain errors

**Steps To Reproduce**
1. Go to graphing mode
2. Type sqrt(y)
3. See error, hover mouse over graph, see crash

**Expected behavior**
No crash

If possible, I would like to fix this.

### PR DESCRIPTION
**Pull request by joseartrivera**
### Description of the changes:
- The call to initialize an empty graph was replaced with a call that tries to graph the error equation

### How changes were validated:
- Type sqrt(y) and hover mouse over graph

### CODE REVIEW

**Comment by joseartrivera** [comment]
> I was still able to repro a crash when I inputted a valid equation, then an invalid one.

Good catch, I was able to fix this on our side but it will result in an empty graph, temporarily not rendering existing valid equations until the equation with an error is fixed by the user. Better than crashing though.

File: src/GraphControl/Control/Grapher.cpp [hunk 1]
```diff
@@ -314,14 +314,18 @@ namespace GraphControl
                         initResult = nullopt;
                     }
                 }
+                else
+                {
+                    shouldKeepPreviousGraph = false;
```
Comment (sanderl) [inline src/GraphControl/Control/Grapher.cpp]: Can we remove the equation with an error and try to graph again?

Comment (joseartrivera) [reply src/GraphControl/Control/Grapher.cpp]: As discussed, this logic was already in place but was not triggering correctly, probably because the way equations get added was slightly changed at some point. Fixed now!
