### PR TITLE
Expand fix for ja era to handle months and days

### LINKED ISSUE #471: Subtracting 1-year from date during Reiwa 1 yields unexpected results.
**Describe the bug**
When using Japanese era globalization settings, adding/subtracting years can yield unexpected results.

**Steps To Reproduce**

1. Set your globalization settings to Japanese and use the Era notation for Calendar format
2. Open calculator and go to date calculation
3. Switch to add/subtract mode
4. Set the date to Reiwa 1-nen May 1
5. Subtract 1 year from that date
6. Note the result is Heisei 31-nen Apr 1

**Expected behavior**

the result should be Heisei 30, May 1
**Screenshots**

**Device and Application Information**
 - OS Build: 17763
 - Architecture: x64
 - Application Version:
 - Region: 
 - Dev Version Installed: 
 

**Additional context**

The Japanese Era system can have multiple year partitions within the same year.
For example, April 30, 2019 is denoted April 30, Heisei 31; May 1, 2019 is denoted as May 1, Reiwa 1.  The Calendar treats Heisei 31 and Reiwa 1 as separate years, which results in some unexpected behaviors where subtracting a year from Reiwa 1 results in a date in Heisei 31.

### PR DESCRIPTION
**Pull request by EriWong**
## Fixes #471
The previous fix only covered how the Calendar control handles years across era boundaries.  It turns out the calendar treats the boundary as a month boundary as well.  So if the transition across eras happens on the 15th of January, then it considers the 16th of January and the 14th of January to be in different months.

### Description of the changes:
-  Uses the Gregorian calendar for all addition and subtraction of dates when in the Japanese era system.

### How changes were validated:

- Manually tested month and day subtraction across era boundaries not at the beginning or end of a month.

### CODE REVIEW

**Comment by sanderl** [comment]
>             break;

Can you check if months is also affected here?

---
Refers to: src/CalcViewModel/Common/DateCalculator.cpp:329 in a268148. [](commit_id = a2681484da1f9fb72c0699db9a8310ba25c05b45, deletion_comment = False)

**Comment by EriWong** [comment]
> > ```
> >         break;
> > ```
> 
> Can you check if months is also affected here?
> 
> Refers to: src/CalcViewModel/Common/DateCalculator.cpp:329 in [a268148](https://github.com/Microsoft/calculator/commit/a2681484da1f9fb72c0699db9a8310ba25c05b45). [](commit_id = [a268148](https://github.com/Microsoft/calculator/commit/a2681484da1f9fb72c0699db9a8310ba25c05b45), deletion_comment = False)

Good catch.  Latest update fixes and tests that as well.  Thanks!

File: src/CalculatorUnitTests/DateCalculatorUnitTests.cpp [hunk 1]
```diff
@@ -697,24 +711,60 @@ namespace DateCalculationUnitTests
             auto cal = ref new Calendar();
 
             // Showa period ended in Jan 1989.
```
Comment (sanderl) [inline src/CalculatorUnitTests/DateCalculatorUnitTests.cpp]: >a [](start = 19, length = 1)

nit: add space

File: src/CalculatorUnitTests/DateCalculatorUnitTests.cpp [hunk 2]
```diff
@@ -697,24 +711,60 @@ namespace DateCalculationUnitTests
...
+
+            VERIFY_ARE_EQUAL(expectedMonthResult.UniversalTime, actualMonthResult.UniversalTime);
+        }
+
+        TEST_METHOD(JaEraTransitionDifference)
+        {
+            auto viewModel = make_unique<DateCalculationEngine>(CalendarIdentifiers::Japanese);
+            auto cal = ref new Calendar();
+
+            // Showa period ended in Jan 8, 1989.  Pick 2 days across that boundary
```
Comment (sanderl) [inline src/CalculatorUnitTests/DateCalculatorUnitTests.cpp]: >a [](start = 19, length = 1)

nit: add space

File: src/CalcViewModel/Common/DateCalculator.cpp [hunk 3]
```diff
@@ -308,27 +307,23 @@ bool DateCalculationEngine::TryGetCalendarDaysInYear(_In_ DateTime date, _Out_ U
 // Adds/Subtracts certain value for a particular date unit
 DateTime DateCalculationEngine::AdjustCalendarDate(Windows::Foundation::DateTime date, DateUnit dateUnit, int difference)
 {
-
     m_calendar->SetDateTime(date);
 
+    // In the Japanese calendar, transition years have 2 partial years.
+    // It is not guaranteed that adding 1 year will always add 365 days in the Japanese Calendar.
+    // To work around this quirk, we will change the calendar system to Gregorian before adding 1 year in the Japanese Calendar case only.
+    // We will then return the calendar system back to the Japanese Calendar.
```
Comment (sanderl) [inline src/CalcViewModel/Common/DateCalculator.cpp]: Let's change this to be the same as the comment above.
