### PR TITLE
Convert DateCalculatorViewModel to runtime class

### LINKED ISSUE #770: Convert DateCalculatorViewModel to runtime class
## Describe the bug
CalcViewModel contains both standard C++ classes and runtime classes (ref class). In order to make our code more homogeneous, we want to convert all public classes of CalcViewModel into runtime classes, including all classes associated to Date Calculator.

## Requested Assignment
If possible, I would like to fix this.

### PR DESCRIPTION
**Pull request by rudyhuyn**
### Description of the changes:
- Convert DateDifference, DateCalculationEngine to runtime class
   - update all DateCalculationEngine methods to not pass arguments by reference
- Convert DateCalculatorViewModel to runtime class
- Update DateCalculatorUnitTest

### How changes were validated:
- manually

### CODE REVIEW

File: src/CalculatorUnitTests/DateCalculatorUnitTests.cpp [hunk 1]
```diff
@@ -955,7 +956,7 @@ TEST_METHOD(DateCalcViewModelAddSubtractResultAutomationNameTest)
 
 TEST_METHOD(JaEraTransitionAddition)
 {
-    auto viewModel = make_unique<DateCalculationEngine>(CalendarIdentifiers::Japanese);
+    auto viewModel = ref new DateCalculationEngine(CalendarIdentifiers::Japanese);
```
Comment (mcooley) [inline src/CalculatorUnitTests/DateCalculatorUnitTests.cpp]: nit: while you're here, let's name the variable "engine" instead of "viewModel" in all the JaEra* tests

File: src/CalculatorUnitTests/DateCalculatorUnitTests.cpp [hunk 2]
```diff
@@ -390,7 +396,7 @@ TEST_METHOD(TestSubtraction)
     //    DateTime endDate;
 
     //    // Subtract Duration
-    //    bool isValid = m_DateCalcEngine.SubtractDuration(DateUtils::SystemTimeToDateTime(datetimeSubtractCase[testIndex].startDate),
+    //    bool isValid = m_DateCalcEngine->SubtractDuration(DateUtils::SystemTimeToDateTime(datetimeSubtractCase[testIndex].startDate),
```
Comment (mcooley) [inline src/CalculatorUnitTests/DateCalculatorUnitTests.cpp]: nit: SubtractDuration no longer returns a bool

(It's okay with me if you won't want to fix these commented-out tests right now.)

File: src/CalculatorUnitTests/DateCalculatorUnitTests.cpp [hunk 3]
```diff
@@ -657,7 +659,7 @@ TEST_METHOD(DateCalcViewModelInitializationTest)
 
 TEST_METHOD(DateCalcViewModelAddSubtractInitTest)
 {
-    auto viewModel = ref new DateCalculatorViewModel();
+    DateCalculatorViewModel ^ viewModel = ref new DateCalculatorViewModel();
```
Comment (mcooley) [inline src/CalculatorUnitTests/DateCalculatorUnitTests.cpp]: nit: prefer using "auto" like it was before. Same feedback for DateCalcViewModelDateDiffDaylightSavingTimeTest

File: src/CalcViewModel/DateCalculatorViewModel.h [hunk 4]
```diff
@@ -22,9 +22,30 @@ namespace CalculatorApp
...
+                    if (m_IsDiffInDays != value)
+                    {
+                        m_IsDiffInDays = value;
+                        RaisePropertyChanged(L"IsDiffInDays");
+                    }
+                }
+            }
+
+        private:
+            bool m_IsDiffInDays;
```
Comment (mcooley) [inline src/CalcViewModel/DateCalculatorViewModel.h]: nit: lowercase "i": "m_isDiffInDays"

**Comment by rudyhuyn** [comment]
PR rebased
