### PR TITLE
Fix some accessibility bugs

### LINKED ISSUE #949: Equation show/hide buttons provide no context via Narrator as to which equation they affect
**Describe the bug**
The equation show/hide buttons provide no additional context to Narrator to inform the user of which equation is affected, and the announced string for the buttons is misleading.

**Steps To Reproduce**

1. Go to the equation editor in Graphing mode.
2. Add an equation.
3. With Narrator on, navigate to the show/hide button.
4. Narrator reads, "[Show | Hide] button, [on | off]." No additional context is given.

**Expected behavior**
Narrator should provide more context to the user as to what the button is showing/hiding.
Additionally, "Show" is always announced as being in the "on" state, and "Hide" is always announced in the "off" state.

Button should retain the same name when toggled while communicating which equation is affected and the state. For example:

"Equation 1 Visibility Button, [Visible/Hidden]"

**Screenshots**

**Device and Application Information**
- OS Build: 10.0.19547.0
- Architecture: x64
- Application Version: 10.1912.4.0
- Region: en-US
- Dev Version Installed:

**Additional context**

**Requested Assignment**

I'm just reporting this problem.  I don't want to fix it.

> Note: A team member updated this comment to clarify expected behavior.

### LINKED ISSUE #1000: Zoom in/Zoom out/Reset tooltips missing shortcut keys
**Describe the bug**
Graph view buttons missing shortcut keys in tooltips.

**Expected behavior**
* Zoom In: "Zoom in (Ctrl+plus)"
* Zoom Out: "Zoom out (Ctrl+minus)"
* Reset View: "Reset view (Ctrl+0)"
  * Shortcut is not working

### PR DESCRIPTION
**Pull request by joseartrivera**
### Description of the changes:
- Updates resw files to fix linked bugs

### How changes were validated:
- Manual tests

### CODE REVIEW

File: src/Calculator/Controls/EquationTextBox.cpp [hunk 1]
```diff
@@ -62,8 +62,12 @@ void EquationTextBox::OnApplyTemplate()
         m_equationButton->Click += ref new RoutedEventHandler(this, &EquationTextBox::OnEquationButtonClicked);
 
         auto toolTip = ref new ToolTip();
+
         auto equationButtonMessage = m_equationButton->IsChecked->Value ? resProvider->GetResourceString(L"showEquationButtonToolTip")
                                                                         : resProvider->GetResourceString(L"hideEquationButtonToolTip");
+
+        equationButtonMessage = LocalizationStringUtil::GetLocalizedString(equationButtonMessage, EquationButtonContentIndex);
```
Comment (EriWong) [inline src/Calculator/Controls/EquationTextBox.cpp]: >LocalizationStringUtil::GetLocalizedString(equationButtonMessage, EquationButtonContentIndex); [](start = 32, length = 94)

Maybe fold this into the previous call?  It feels a bit odd to assign a value and the immediately reassign it...
ie:
m_equationButton->IsChecked->Value ? LocalizationStringUtil::GetLocalizedString(resProvider->GetResourceString(L"showEquationButtonToolTip"), EquationButtonContentIndex) : ...

Comment (joseartrivera) [reply src/Calculator/Controls/EquationTextBox.cpp]: fixed!
