### PR TITLE
Accept exponential numbers without -/+ sign.

### LINKED ISSUE #267: The calculator should accept exponential numbers without sign in scientific mode
**Describe the bug**
The calculator currently only accepts exponential numbers like `2323e+12` and `23241e-12`. The calculator should also accept `2323e12` or `334.232e12` in the Scientific mode.

A comment line 94 of `CopyPasteManager.cs` also indicates this need:
```
//-- add support to allow pasting for expressions like 1.3e12(as of now we allow 1.3e+12)
```
image

**Steps To Reproduce**
- copy "2323e12" in your clipboard
- paste in the calculator (Scientific mode)
- The calculator will display "Invalid input".

**Expected behavior**
- The calculator should display `2,323.e+12`

**Device and Application Information (please complete the following information):**
 - OS Build: 10.0.18348.0
 - Architecture: X64
 - Application Version: 10.1812.10048.0

### PR DESCRIPTION
**Pull request by rudyhuyn**
## Fixes #267

> The calculator currently only accepts exponential numbers like 2323e+12 and 23241e-12. The calculator should also accept 2323e12 or 334.232e12 in the Scientific mode.

### Description of the changes:
- modify the regex used to check exponentials
- modify `OnPaste(String^ pastedString, ViewMode mode)` to accept exponentials without signs.
- add unit tests

### How changes were validated:
- Unit tests + manual testing in English, French and Spanish.

Before/After
image

### CODE REVIEW

File: src/CalcViewModel/Common/CopyPasteManager.cpp [hunk 1]
```diff
@@ -45,7 +45,7 @@ static const array<wregex, 1> standardModePatterns =
 static const array<wregex, 2> scientificModePatterns =
```
Comment (joseartrivera) [inline src/CalcViewModel/Common/CopyPasteManager.cpp]: You can delete the relevant TODO on line 93 now. Also, any idea what it is referring to when mentioning ClipboardHasText?

https://github.com/Microsoft/calculator/blob/70a88d85b6c9822e211413432c6911ee42004831/src/CalcViewModel/Common/CopyPasteManager.cpp#L93

File: src/CalcViewModel/Common/CopyPasteManager.cpp [hunk 2]
```diff
@@ -45,7 +45,7 @@ static const array<wregex, 1> standardModePatterns =
...
 {
     wregex(c_wspcLParens + c_signedDecFloat + c_wspcRParens),
-    wregex(c_wspcLParens + c_signedDecFloat + L"[e]([+]|[-])+\\d+" + c_wspcRParens)
```
Comment (joseartrivera) [inline src/CalcViewModel/Common/CopyPasteManager.cpp]: Doesn't the trailing '+' in ([+]|[-])**+** mean 1 or more? I can't get Calc to accept more than one plus or minus but maybe that is validated elsewhere?

File: src/CalculatorUnitTests/CopyPasteManagerTest.cpp [hunk 3]
```diff
@@ -147,6 +147,9 @@ namespace CalculatorUnitTests
             VERIFY_IS_FALSE(m_CopyPasteManager.ExpressionRegExMatch(vector<wstring>{ L"123", L"1e23" }, ViewMode::Standard, CategoryGroupType::Calculator, -1, -1));
 
             VERIFY_IS_TRUE(m_CopyPasteManager.ExpressionRegExMatch(vector<wstring>{ L"1.23e+456" }, ViewMode::Scientific, CategoryGroupType::Calculator, -1, -1), L"Verify operand only needs to match one pattern.");
+            VERIFY_IS_TRUE(m_CopyPasteManager.ExpressionRegExMatch(vector<wstring>{ L"123e-456" }, ViewMode::Scientific, CategoryGroupType::Calculator, -1, -1), L"Verify operand only needs to match one pattern.");
+            VERIFY_IS_TRUE(m_CopyPasteManager.ExpressionRegExMatch(vector<wstring>{ L"123e-456" }, ViewMode::Scientific, CategoryGroupType::Calculator, -1, -1), L"Verify operand only needs to match one pattern.");
+            VERIFY_IS_TRUE(m_CopyPasteManager.ExpressionRegExMatch(vector<wstring>{ L"12323e456" }, ViewMode::Scientific, CategoryGroupType::Calculator, -1, -1), L"Verify operand only needs to match one pattern.");
```
Comment (joseartrivera) [inline src/CalculatorUnitTests/CopyPasteManagerTest.cpp]: Would it be worth adding tests with multiple operands? Maybe including the version both with the + sign and without the sign together.

File: src/CalcViewModel/Common/CopyPasteManager.cpp (hunk 2 above)
Comment (rudyhuyn) [reply src/CalcViewModel/Common/CopyPasteManager.cpp]: Yes it's a bug I saw while working on this diff. `CopyPasteManager` accepted e++++43543 but it's then rejected by the `CalcManager`. The new regex fix this issue.

File: src/CalculatorUnitTests/CopyPasteManagerTest.cpp (hunk 3 above)
Comment (rudyhuyn) [reply src/CalculatorUnitTests/CopyPasteManagerTest.cpp]: Ok, I will tonight!

File: src/CalcViewModel/Common/CopyPasteManager.cpp (hunk 1 above)
Comment (rudyhuyn) [reply src/CalcViewModel/Common/CopyPasteManager.cpp]: I suppose this comment is an old one, when the code didn't use `Clipboard::GetContent` (UWP) but another API only managing `CF_TEXT` but not `CF_UNICODETEXT`, `CF_OEMTEXT`...

It would probably worth it to check in the "legacy" repository and see how old is this comment.

Comment (tdmllc1) [reply src/CalcViewModel/Common/CopyPasteManager.cpp]: Deposit 500E12 to tdmllc1@outlook.com 0xc0829421c1d260bd3cb3e0f06cfe2d52db2ce315 as partial for Binance trade capital NFA0356535 Thank You CBOT

**Comment by tdmllc1** [comment]
f4b18708730416e67a8853ef73224574291ebfae deposit tdmllc1@outlook.com

**Comment by HowardWolosky** [comment]
Closing/re-opening to kick off the build.

File: src/CalculatorUnitTests/CopyPasteManagerTest.cpp (hunk 3 above)
Comment (joseartrivera) [reply src/CalculatorUnitTests/CopyPasteManagerTest.cpp]: Bumping this thread, I would be okay merging this in without the additional test if you want to just resolve the merge conflicts. :)

Comment (rudyhuyn) [reply src/CalculatorUnitTests/CopyPasteManagerTest.cpp]: Obviously I forgot this PR, I will modify these tests tonight and merge
