### PR TITLE
Fix #222: Wrong result for e.g. √(2.25) - 1.5 #222

### LINKED ISSUE #222: Wrong result for e.g. √(2.25) - 1.5
**Describe the bug**

√(2.25) is 1.5 and the result shown is correct. However, subtracting 1.5 from that shows an incorrect result such as -2.1115953280960553738983525708397e-38.

This bug happens in all equivalent cases, e.g. with √(0.81) or any other square root that is a terminating decimal.

**Steps To Reproduce**
1. Use standard or scientific mode
2. Enter 2.25
3. Press √
4. Subtract 1.5
5. Result is wrong

**Expected behavior**

Result is 0

**Device and Application Information (please complete the following information):**
 - OS Build: 10     0      17763  0
 - Architecture: X64
 - Application Version: 10.1812.10048.0

**Additional info**
Until recently, it also used to be that "√(4) - 2" didn't result in 0. It was fixed in the UWP app, but is a bug in calc.exe in older versions of Windows.

### PR DESCRIPTION
**Pull request by guihuaz**
### Description of the changes:
- add a helper function _snaprat to check if a result RAT should be zero with given precision. Apply _snaprat to addrat/subrat/lograt.
- The root causes of issues #222, #309, #574 are the same. For an irrational number result, the approximation introduces small errors beyond precision required, which is expected. The issue was Ratpak tried to take "precision" digits from the calculation result regardless where the result came from, and it exposed digits from approximation errors. Take `sqrt(2.25) - 1.5` for example. `sqrt(2.25)` might be approximated to `1.499...998...` depending on the precision. When this number subtracted `1.5`, the Ratpak got `0.000...001....` Ratpak took up to precision number of digits and converts to scientific format, which resulted `-1.2566515751494548126925332972115e-47`. This PR checks the magnitude difference between the result and the input operands. Since the result is too close to `47` magnitude smaller than original subtraction operands `1.499...998...` and `1.5`, it would be snapped to `0`.
- The same fix applies to `lograt` as well. 
- One further optimization could be a new sqrt function specifically checking perfect square first before using Taylor series approximation.

### How changes were validated:

- Add 1 test case in `CalculatorManagerTestStandard` to verify addrat. 
- Add 2 test cases in `CalculatorManagerTestScientific` to verify addrat and lograt
- Manual test the cases in the linked issues.
- Manual test log case: `log(sqrt(2.25)/1.5)`

### CODE REVIEW

**Comment by tian-lt** [comment]
> @tian-lt, are you the maintainer of this repo? Could you please take a look at the PR?

@guihuaz Sure. Thank you for proposing the fix.
Let me trigger a CI run for this PR.
I'll review the changes and get back to you later.

**Comment by tian-lt** [comment]
@guihuaz 
Shall we adjust the result in the `Rational` class or a higher context? Because treating the epsilon as zero is more like an application requirement rather than a correct behavior of semi-numerical analysis.

**Review by tian-lt — APPROVED** [review]

**Comment by tian-lt** [comment]
The changes look good to me.
@HuanglinXu21 @guominrui, could you help take a look?

**Comment by axtar** [comment]
It seems that this PR has broken lograt. For example log of 9.e+99 now returns 0 instead of 99.954...

**Comment by guihuaz** [comment]
> It seems that this PR has broken lograt. For example log of 9.e+99 now returns 0 instead of 99.54...

@axtar do you have dev env? If so, could you please try to try removing _snaprat inside lograt to see if it fixes the issue? I'm not on my windows machine, right now. I might have time to try this weekend.

**Comment by axtar** [comment]
@guihuaz removing _snaprat in lograt fixes the problem but then of course the problem with log( tan₀( 45 ) ) reappears.

**Comment by axtar** [comment]
@guihuaz As a temporary solution, I added a check in my project so that _snaprat only snaps to zero if absR is also smaller than rat_smallest.

File: src/CalcManager/Ratpack/rat.cpp [hunk 1]
```diff
@@ -285,3 +313,76 @@ bool zerrat(_In_ PRAT a)
...
+        destroyrat(absB);
+    }
+    mulrat(&threshold, rat_smallest, precision);
+
+    PRAT absR = nullptr;
+    DUPRAT(absR, *pr);
+    ABSRAT(absR);
+
+    // if absResult < threshold => snap to zero
+    if (rat_lt(absR, threshold, precision))
```
Comment (guihuaz) [inline src/CalcManager/Ratpack/rat.cpp:381]: (@axtar , move comment here to have a thread)
Do you add a check here? I think this is safe change. Could you please send a PR to add the additional check absR < rat_smallest?

It may expose some other edge cases back, but _snaprat does not likely catch all these cases. In my understanding, the issue is fundamental design flaw in Ratpack. Ratpack, as the name implies, is for arbitrary precision rational math. But it tries to include some irrational math using approximation and rounding. I think this would inevitably introduce errors.

Comment (axtar) [reply src/CalcManager/Ratpack/rat.cpp:381]: Yes, I have added an “&&” to that “if”.
I’m sorry but I don’t have the skills to contribute to this repository. I don’t even really know how to make a pull request. I’m simply using ratpak on a microcontroller for a hobbyist hardware calculator project. That’s why I found the issue.
Approximation and rounding issues are difficult to fix but for a calculator arbitrary precision is always better than 64-bit floating point arithmetic. I really like ratpak, it's small and very efficient. But it has a lot of memory leaks that I had to fix to run it on a microcontroller.

Comment (axtar) [reply src/CalcManager/Ratpack/rat.cpp:381]: I have opened an issue for this
